CREATE DATABASE JDO_DB18986;
GO
USE AMG_DB18986;
GO
CREATE TABLE CATEGORIES (
    CATEGORY_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(MAX),
    PICTURE VARCHAR(30),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_CATEGORY_NAME (CATEGORY_NAME),
    INDEX IDX_DESCRIPTION (DESCRIPTION)
);
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID CHAR(20) PRIMARY KEY,
    COMPANY_NAME VARCHAR(40),
    CONTACT_NAME VARCHAR(30),
    CONTACT_TITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY CHAR(15),
    REGION CHAR(15),
    POSTAL_CODE CHAR(10),
    COUNTRY CHAR(15),
    PHONE CHAR(24),
    FAX CHAR(24),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_COMPANY_NAME (COMPANY_NAME)
);
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    LAST_NAME VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    TITLE CHAR(30),
    TITLE_OF_COURTESY CHAR(25),
    BIRTH_DATE DATE,
    HIRE_DATE DATE,
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    HOME_PHONE VARCHAR(24),
    EXTENSION VARCHAR(24),
    PHOTO VARCHAR(50),
    NOTES NVARCHAR(MAX),
    REPORTS_TO SMALLINT,
    PHOTO_PATH VARCHAR(255),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_LAST_NAME (LAST_NAME),
    INDEX IDX_FIRST_NAME (FIRST_NAME),
    FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
CREATE TABLE TERRITORIES (
    TERRITORY_ID CHAR(20) PRIMARY KEY,
    TERRITORY_DESCRIPTION VARCHAR(100) NOT NULL,
    REGION_ID SMALLINT NOT NULL,
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_TERRITORY_DESCRIPTION (TERRITORY_DESCRIPTION),
    FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID)
);
CREATE TABLE EMPLOYEE_TERRITORIES (
    EMPLOYEE_ID SMALLINT NOT NULL,
    TERRITORY_ID CHAR(20) NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID, TERRITORY_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORIES(TERRITORY_ID)
);
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    COMPANY_NAME VARCHAR(40),
    CONTACT_NAME VARCHAR(30),
    CONTACT_TITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY CHAR(15),
    REGION CHAR(15),
    POSTAL_CODE CHAR(10),
    COUNTRY CHAR(15),
    PHONE CHAR(24),
    FAX CHAR(24),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_COMPANY_NAME (COMPANY_NAME)
);
CREATE TABLE PRODUCTS (
    PRODUCT_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    SUPPLIER_ID SMALLINT,
    CATEGORY_ID SMALLINT,
    QUANTITY_PER_UNIT CHAR(20),
    UNIT_PRICE MONEY CHECK (UNIT_PRICE > 0),
    UNITS_IN_STOCK SMALLINT,
    UNITS_ON_ORDER SMALLINT,
    REORDER_LEVEL SMALLINT,
    DISCONTINUED INT NOT NULL,
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_PRODUCT_NAME (PRODUCT_NAME),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);
CREATE TABLE REGION (
    REGION_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    REGION_DESCRIPTION VARCHAR(100) NOT NULL,
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_REGION_DESCRIPTION (REGION_DESCRIPTION)
);
CREATE TABLE SHIPPERS (
    SHIPPER_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    COMPANY_NAME VARCHAR(40) NOT NULL,
    PHONE VARCHAR(24),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_COMPANY_NAME (COMPANY_NAME)
);
CREATE TABLE ORDERS (
    ORDER_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID CHAR(40) NOT NULL,
    EMPLOYEE_ID SMALLINT,
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE CHECK (SHIPPED_DATE >= ORDER_DATE),
    SHIP_VIA SMALLINT,
    FREIGHT MONEY CHECK (FREIGHT > 0),
    SHIP_NAME CHAR(40),
    SHIP_ADDRESS CHAR(60),
    SHIP_CITY CHAR(15),
    SHIP_REGION CHAR(15),
    SHIP_POSTAL_CODE CHAR(10),
    SHIP_COUNTRY CHAR(15),
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_EMPLOYEE_ID (EMPLOYEE_ID),
    INDEX IDX_ORDER_DATE (ORDER_DATE),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (SHIP_VIA) REFERENCES SHIPPERS(SHIPPER_ID)
);
CREATE TABLE ORDER_DETAILS (
    ORDER_ID SMALLINT NOT NULL,
    PRODUCT_ID SMALLINT NOT NULL,
    UNIT_PRICE MONEY NOT NULL CHECK (UNIT_PRICE > 0),
    QUANTITY SMALLINT NOT NULL CHECK (QUANTITY > 0),
    DISCOUNT MONEY NOT NULL,
    DATE_CREATED DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
CREATE PROCEDURE PopulateTables
AS
BEGIN
    -- Insert data into CATEGORIES
    INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, PICTURE)
    VALUES 
        ('BEVERAGES', 'SOFT DRINKS, COFFEES, TEAS, BEERS, AND ALES', 'X'),
        ('CONDIMENTS', 'SWEET AND SAVORY SAUCES, RELISHES, SPREADS, AND SEASONINGS', 'X'),
        ('CONFECTIONS', 'DESSERTS, CANDIES, AND SWEET BREADS', 'X'),
        ('DAIRY PRODUCTS', 'CHEESES', 'X'),
        ('GRAINS/CEREALS', 'BREADS, CRACKERS, PASTA, AND CEREAL', 'X'),
        ('MEAT/POULTRY', 'PREPARED MEATS', 'X'),
        ('PRODUCE', 'DRIED FRUIT AND BEAN CURD', 'X'),
        ('SEAFOOD', 'SEAWEED AND FISH', 'X');

    -- Insert data into CUSTOMERS
    INSERT INTO CUSTOMERS (CUSTOMER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
    VALUES 
        ('ALFKI', 'ALFREDS FUTTERKISTE', 'MARIA ANDERS', 'SALES REPRESENTATIVE', 'OBERE STR. 57', 'BERLIN', NULL, '12209', 'GERMANY', '030-0074321', '030-0076545'),
        ('ANATR', 'ANA TRUJILLO EMPAREDADOS Y HELADOS', 'ANA TRUJILLO', 'OWNER', 'AVDA. DE LA CONSTITUCIÓN 2222', 'MEXICO D.F.', '5021', 'MEXICO', '(5) 555-4729', '(5) 555-3745'),
        ('ANTON', 'ANTONIO MORENO TAQUERÍA', 'ANTONIO MORENO', 'OWNER', 'MATADEROS 2312', 'MEXICO D.F.', '5023', 'MEXICO', '(5) 555-3932', NULL),
        ('AROUT', 'AROUND THE HORN', 'THOMAS HARDY', 'SALES REPRESENTATIVE', '120 HANOVER SQ.', 'LONDON', 'WA1 1DP', 'UK', '(171) 555-7788', '(171) 555-6750'),
        ('BERGS', 'BERGLUNDS SNABBKÖP', 'CHRISTINA BERGLUND', 'ORDER ADMINISTRATOR', 'BERGUVSVÄGEN 8', 'LULEÅ', 'S-958 22', 'SWEDEN', '0921-12 34 65', '0921-12 34 67');

    -- Insert data into EMPLOYEES
    INSERT INTO EMPLOYEES (LAST_NAME, FIRST_NAME, TITLE, TITLE_OF_COURTESY, BIRTH_DATE, HIRE_DATE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, HOME_PHONE, EXTENSION, PHOTO, NOTES, REPORTS_TO)
    VALUES
        ('DAVOLIO', 'NANCY', 'SALES REPRESENTATIVE', 'MS.', '1948-12-08', '1992-05-01', '507 - 20TH AVE. E. NAPT. 2A', 'SEATTLE', 'WA', '98122', 'USA', '(206) 555-9857', '5467', NULL, 'EDUCATION INCLUDES A BA IN PSYCHOLOGY FROM COLORADO STATE UNIVERSITY IN 1970. SHE ALSO COMPLETED THE ART OF THE COLD CALL. NANCY IS A MEMBER OF TOASTMASTERS INTERNATIONAL.', 2),
        ('FULLER', 'ANDREW', 'VICE PRESIDENT, SALES', 'DR.', '1952-02-19', '1992-08-14', '908 W. CAPITAL WAY', 'TACOMA', 'WA', '98401', 'USA', '(206) 555-9482', '3457', NULL, 'ANDREW RECEIVED HIS BTS COMMERCIAL IN 1974 AND A PH.D. IN INTERNATIONAL MARKETING FROM THE UNIVERSITY OF DALLAS IN 1981. HE IS FLUENT IN FRENCH AND ITALIAN AND READS GERMAN.', 2);

    -- Insert data into REGION
    INSERT INTO REGION (REGION_DESCRIPTION)
    VALUES 
        ('EASTERN'),
        ('WESTERN'),
        ('NORTHERN'),
        ('SOUTHERN');

    -- Insert data into TERRITORIES
    INSERT INTO TERRITORIES (TERRITORY_ID, TERRITORY_DESCRIPTION, REGION_ID)
    VALUES 
        ('01581', 'WESTBORO', 1),
        ('01730', 'BEDFORD', 1),
        ('01833', 'GEORGETOW', 1),
        ('02116', 'BOSTON', 1),
        ('02139', 'CAMBRIDGE', 1),
        ('02184', 'BRAINTREE', 1),
        ('02903', 'PROVIDENCE', 1);

    -- Insert data into EMPLOYEE_TERRITORIES
    INSERT INTO EMPLOYEE_TERRITORIES (EMPLOYEE_ID, TERRITORY_ID)
    VALUES 
        (2, '01581'),
        (2, '01730'),
        (2, '01833'),
        (2, '02116'),
        (2, '02139');

    -- Insert data into SUPPLIERS
    INSERT INTO SUPPLIERS (COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
    VALUES 
        ('EXOTIC LIQUIDS', 'CHARLOTTE COOPER', 'PURCHASING MANAGER', '49 GILBERT ST.', 'LONDON', 'EC1 4SD', 'UK', '(171) 555-2222'),
        ('NEW ORLEANS CAJUN DELIGHTS', 'SHELLEY BURKE', 'ORDER ADMINISTRATOR', 'P.O. BOX 78934', 'NEW ORLEANS', 'LA', '70117', 'USA', '(100) 555-4822', NULL);

    -- Insert data into PRODUCTS
    INSERT INTO PRODUCTS (PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
    VALUES 
        ('CHAI', 2, 1, '10 BOXES X 30 BAGS', 18.39, 0, 10, 1, 1),
        ('ANISEED SYRUP', 2, 2, '12 - 550 ML BOTTLES', 10.13, 70, 25, 0, 1);

    -- Insert data into SHIPPERS
    INSERT INTO SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE)
    VALUES 
        (1, 'SPEEDY EXPRESS', '(503) 555-9831'),
        (2, 'UNITED PACKAGE', '(503) 555-3199');
    
    -- Insert data into ORDERS
    INSERT INTO ORDERS (CUSTOMER_ID, EMPLOYEE_ID, ORDER_DATE, REQUIRED_DATE, SHIPPED_DATE, SHIP_VIA, FREIGHT, SHIP_NAME, SHIP_ADDRESS, SHIP_CITY, SHIP_REGION, SHIP_POSTAL_CODE, SHIP_COUNTRY)
    VALUES 
        ('ALFKI', 2, '1997-08-25', '1997-09-22', '1997-09-02', 1, 29.46, 'ALFREDS FUTTERKISTE', 'OBERE STR. 57', 'BERLIN', '12209', 'GERMANY');
    
    -- Insert data into ORDER_DETAILS
    INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
    VALUES 
        (1, 1, 18.39, 10, 0);
    
END;
GO